site_django/blog/urls.py
from django.urls import path
from . import views

app_name = "blog"

urlpatterns = [
    path("", views.index, name="index"),
    path("detail/<int:pk>/", views.blog_detail, name = "blog_detail"),
    path("create/", views.create_blog, name = "create_blog"),
    path("update/<int:pk>/", views.update_blog, name="update_blog"),
    path("delete/<int:pk>/", views.delete_blog, name="delete_blog"),
    path("contacts/", views.contacts, name = "contacts"),
]

site_django/site_django/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),  # Панель администратора
    path("", include("blog.urls"), name = "blog"), # Подключаем маршруты "Блога"
    path("users/", include("users.urls"), name = "users"),
] + static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

site_django/users/urls.py
from django.urls import path
from . import  views

app_name = "users"
urlpatterns = [
    path("login/", views.Login.as_view(), name ="login"),
    path("logout/", views.Logout.as_view(), name="logout"),
    path("register/", views.register, name="register"),
    path("profile/", views.profile, name="profile"),
    path("profile_update", views.profile_update, name="profile_update"),
]

site_django/users/models.py
from django.db import models

# Create your models here.

site_django/users/forms.py
from django import forms
from  django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User

class AuthUserForm(AuthenticationForm, forms.ModelForm):
    class Meta:
        model = User
        fields = ["username", "password"]
        
    def __init__(self, *args, **kwargs):
        super(AuthUserForm, self).__init__(*args, **kwargs)
        self.fields["username"].label = ""
        self.fields["password"].label = ""
        self.fields["username"].widget = forms.TextInput(
            attrs={
                "placeholder": "Имя пользователя",
                "class": "form-control",
            }
        )

        self.fields["password"].widget = forms.TextInput(
            attrs={
                "placeholder": "Пароль",
                "class": "form-control",
            }
        )

class UserRegistrationForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super(UserRegistrationForm, self).__init__(*args, **kwargs)
        self.fields["username"].label = ""
        self.fields["password1"].label = ""
        self.fields["password2"].label = ""
        self.fields["username"].widget = forms.TextInput(
            attrs={
                "placeholder": "Имя пользователя",
                "class": "form-control",
            }
        )

        self.fields["password1"].widget = forms.TextInput(
            attrs={
                "placeholder": "Пароль",
                "class": "form-control",
            }
        )

        self.fields["password2"].widget = forms.TextInput(
            attrs={
                "placeholder": "Подтвердите пароль",
                "class": "form-control",
            }
        )

class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ["username", "first_name", "last_name", "email"]

    def __init__(self, *args, **kwargs):
        super(UserUpdateForm, self).__init__(*args, **kwargs)
        self.fields["username"].label = ""
        self.fields["username"].help_text = ""
        self.fields["username"].widget = forms.TextInput(
            attrs={
                "placeholder": "Имя пользователя",
                "class": "form-control",
            }
        )

        self.fields["first_name"].label = ""
        self.fields["first_name"].help_text = ""
        self.fields["first_name"].widget = forms.TextInput(
            attrs={
                "placeholder": "Имя",
                "class": "form-control",
            }
        )

        self.fields["last_name"].label = ""
        self.fields["last_name"].help_text = ""
        self.fields["last_name"].widget = forms.TextInput(
            attrs={
                "placeholder": "Фамилия",
                "class": "form-control",
            }
        )

        self.fields["email"].label = ""
        self.fields["email"].help_text = ""
        self.fields["email"].widget = forms.TextInput(
            attrs={
                "placeholder": "Электронная почта",
                "class": "form-control",
            }
        )

site_django/users/views.py
from datetime import datetime

from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LoginView, LogoutView
from django.shortcuts import render, redirect

from .forms import AuthUserForm, UserRegistrationForm, UserUpdateForm


# Create your views here.
class Login(LoginView):
    fields = ["username", "password"]
    template_name = 'users/login.html'
    form_class = AuthUserForm

class Logout(LogoutView):
    template_name = 'users/logout.html'


def register(request):
    regform = UserRegistrationForm(request.POST)
    if request.method == "POST":
        if regform.is_valid():
            reg_f = regform.save(commit=False)
            reg_f.is_active = True
            reg_f.is_staff = False
            reg_f.is_superuser = False
            reg_f.date_joined = datetime.now()
            reg_f.last_login = datetime.now()
            reg_f.save()

            reg_f.backend = 'django.contrib.auth.backends.ModelBackend'
            login(request, reg_f)
            return redirect('blog:index')
    else:
        regform = UserRegistrationForm()
    return render(request, 'users/registration.html', {"regform": regform})

def profile(request):
    user_blogs = request.user.blogpost_set.all()
    return render(request, 'users/profile.html', {"user_blogs": user_blogs})

@login_required
def profile_update(request):
    if request.method == "POST":
        form = UserUpdateForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('users:profile')
    else:
        form = UserUpdateForm(instance=request.user)
    return render(request, 'users/profile_update.html', {"form": form})

site_django/users/templates/users/login.html
 {% extends 'blog/layout.html' %}
 {% load static %}
 {% block title %} Auth {% endblock %}


 {% block static %}
    <link  rel="stylesheet" href="{% static 'users/css/user_form.css' %}">
 {% endblock %}

 {% block content %}
    <a class="title">Войти в аккаунт</a>
    <div class="div_form">
       <div class="form">
        <form method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-outline-primary">Войти</button>
        </form>
       </div>
    </div>
 {% endblock %}

site_django/users/templates/users/profile.html
 {% extends 'blog/layout.html' %}
 {% load static %}
 {% block title %} Profile {% endblock %}


 {% block static %}
    <link  rel="stylesheet" href="{% static 'users/css/profile.css' %}">
 {% endblock %}

 {% block content %}
    <main>
        <section>
            <h2>Информация о пользователе <a href="{% url 'users:profile_update' %}"><i class="fa fa-edit"></i></a></h2>
            <a><strong>Имя пользователя: </strong>{% if user.username%} {{user.username}}{% else %} --- {% endif %}</a><br>
            <a><strong>Электронная почта: </strong>{% if user.email %} {{user.email}}{% else %} --- {% endif %}</a><br>
            <a><strong>Имя: </strong>{% if user.first_name%} {{user.first_name }}{% else %} --- {% endif %}</a><br>
            <a><strong>Фамилия: </strong>{% if user.last_name %} {{user.last_name }}{% else %} --- {% endif %}</a><br>
            <a><strong>Дата регистрации: </strong>{% if user.date_joined%} {{user.date_joined}}{% else %} --- {% endif %}</a><br>
            {% if user.is_staff %}
                <a ><strong>Администратор: </strong> {% if user.is_staff %} Да {% else %} Нет {% endif %}</a><br>
                <a ><strong>Суперпользователь: </strong> {% if user.is_superuser %} Да {% else %} Нет {% endif %}</a><br>
            {% endif %}
        </section>
        <section  class="user-blogs">
            <h2>Блоги пользователя</h2>
            {% if user_blogs %}
                <div class="blogs">
                    {% for blog in user_blogs %}
                         <a href="{% url 'blog:blog_detail' blog.id %}"> {{blog.title}}</a>
                    {% endfor %}
                </div>
            {% else %}
                <a>Пользователь еще не написал ни одного поста</a>
            {% endif %}
        </section>
    </main>
 {% endblock %}

site_django/users/templates/users/profile_update.html
 {% extends 'blog/layout.html' %}
 {% load static %}
 {% block title %} Profile Update{% endblock %}


 {% block static %}
    <link  rel="stylesheet" href="{% static 'users/css/user_form.css' %}">
 {% endblock %}

 {% block content %}
     <a class="title">Редактирование профиля</a>
    <div class="div_form">
       <div class="form">
        <form method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-outline-info">Обновить</button>
        </form>
       </div>
    </div>
 {% endblock %}

site_django/users/templates/users/registration.html
 {% extends 'blog/layout.html' %}
 {% load static %}
 {% block title %} Registration {% endblock %}


 {% block static %}
    <link  rel="stylesheet" href="{% static 'users/css/user_form.css' %}">
 {% endblock %}

 {% block content %}
        <a class="title">Регистрация</a>
    <div class="div_form">
       <div class="form">
            <form method="POST">
                {% csrf_token %}
                {{ regform.as_p }}
                <button type="submit" class="btn btn-outline-primary"> Зарегистрироваться </button>
            </form>
       </div>
    </div>
 {% endblock %}