site_django/blog/urls.py
from django.urls import path
from . import views

app_name = "blog"

urlpatterns = [
    path("", views.index, name="index"),
    path("detail/<int:pk>/", views.blog_detail, name = "blog_detail"),
    path("create/", views.create_blog, name = "create_blog"),
    path("update/<int:pk>/", views.update_blog, name="update_blog"),
    path("delete/<int:pk>/", views.delete_blog, name="delete_blog"),
    path("contacts/", views.contacts, name = "contacts"),
]

site_django/site_django/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),  # Панель администратора
    path("", include("blog.urls"), name = "blog"), # Подключаем маршруты "Блога"
    path("users/", include("users.urls"), name = "users"),
] + static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

site_django/users/urls.py
from django.urls import path
from . import  views

app_name = "users"
urlpatterns = [
    path("login/", views.Login.as_view(), name ="login"),
    path("logout/", views.Logout.as_view(), name="logout"),
    path("register/", views.register, name="register"),
    path("profile/", views.profile, name="profile"),
    path("profile_update", views.profile_update, name="profile_update"),
]

site_django/blog/models.py
from django.contrib.auth.models import User
from django.utils import timezone
from django.db import models
from django.urls import reverse


class BlogPost(models.Model):
    title = models.CharField(max_length=200, verbose_name="Заголовок")
    content = models.TextField(verbose_name="Содержание")
    date_published = models.DateTimeField(default=timezone.now ,verbose_name="Дата публикации")
    image = models.ImageField(upload_to="images/", verbose_name="Изображение")
    author = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="Автор", null=True, blank=True)

    def __str__(self):
        return str(self.title)

    def get_absolute_url(self):
        return reverse("blog:blog_detail", kwargs={"pk": self.pk})

    class Meta:
        verbose_name = "Блог"
        verbose_name_plural = "Блоги"


class Comment(models.Model):
    blog = models.ForeignKey(BlogPost, on_delete=models.CASCADE, verbose_name="Блог")
    author = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="Автор", null=True, blank=True)
    text = models.TextField(verbose_name="Текст комментария")
    date_published = models.DateTimeField(default=timezone.now, verbose_name="Дата публикации")

    def __str__(self):
        return str(self.text)

    class Meta:
        verbose_name = "Комментарий"
        verbose_name_plural = "Комментарии"

site_django/blog/forms.py
from django.forms import ModelForm
from .models import BlogPost, Comment
from django import forms

class BlogPostModelForm(ModelForm):

    class Meta:
        model = BlogPost
        fields = ["title", "content", "image"]

    def __init__(self, *args, **kwargs):
        super(BlogPostModelForm, self).__init__(*args, **kwargs)
        self.fields["title"].help_text = ""
        self.fields["title"].label = ""
        self.fields["title"].widget = forms.Textarea(
            attrs={
                "placeholder": "Название блога",
                "rows": 1,
                "class": "form-control",
            }
        )

        self.fields["content"].help_text = ""
        self.fields["content"].label = ""
        self.fields["content"].widget = forms.Textarea(
            attrs={
                "placeholder": "Содержание",
                "rows": 10,
                "class": "form-control",
            }
        )

class CommentModelForm(ModelForm):
    class Meta:
        model = Comment
        fields = ["text"]

    def __init__(self, *args, **kwargs):
        super(CommentModelForm, self).__init__(*args, **kwargs)
        self.fields["text"].help_text = ""
        self.fields["text"].label = ""
        self.fields["text"].widget = forms.Textarea(
            attrs={
                "placeholder": "Текст комментария",
                "rows": 1,
                "class": "form-control",
            }
        )

site_django/blog/views.py
from datetime import datetime
from re import search

from django.contrib.auth.decorators import login_required, permission_required
from django.core.paginator import Paginator
from django.shortcuts import render, redirect
from .forms import BlogPostModelForm, CommentModelForm
from .models import BlogPost, Comment
# Create your views here.


def index(request):
    blogs = BlogPost.objects.all()
    search = request.GET.get("search")

    if search:
        blogs = blogs.filter(title__icontains=search)

#-----Сортировка по дате ------------------------------------------

    sort_by = request.GET.get("sort")

    if sort_by == 'newest':
        blogs = blogs.order_by('-date_published')  # Сначала новые
    elif sort_by == 'oldest':
        blogs = blogs.order_by('date_published')  # Сначала старые

# ---------------------------------------------------------
    paginator = Paginator(blogs, per_page=5)

    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)

    title = "Главная страница"
    return render(request, 'blog/blog_list.html', {"page_obj":page_obj, "title":title, "sort_by": sort_by})

def blog_detail(request, pk):
    try:
        blog = BlogPost.objects.get(pk=pk)

    except BlogPost.DoesNotExist:
        return render(request, 'blog/blog_detail.html', {"exception": "Такого блога не существует"})

    blogs = BlogPost.objects.all()

    title = blog.title

    count = str(request.GET.get("post"))
    comments = Comment.objects.filter(blog=blog).order_by("date_published")

    if count == "prev":
        if blog.id == blogs.first().id:
            return redirect("blog:blog_detail", pk=blogs.last().id)
        prev_blog = blogs.filter(id__lt=blog.id).last()
        return redirect("blog:blog_detail", pk=prev_blog.id)

    if count == "next":
        if blog.id == blogs.last().id:
            return redirect("blog:blog_detail", pk=blogs.first().id)
        next_blog = blogs.filter(id__gt=blog.id).first()
        return redirect("blog:blog_detail", pk=next_blog.id)

    centext = {
        "blog": blog,
        "title": title,
        "comments": comments
    }

    if request.method == "POST":
        form = CommentModelForm(request.POST)
        if form.is_valid():
            new_comment = form.save(commit=False)
            new_comment.author =request.user
            new_comment.date_published = datetime.now()
            new_comment.blog = blog
            new_comment.save()
            return redirect("blog:blog_detail", pk=pk)
    else:
        form = CommentModelForm()
    centext["form"] = form
    return render(request, 'blog/blog_detail.html', centext)


@permission_required("blog.add_blogpost")
@login_required
def create_blog(request):
    title = "Создание блога"
    action = "Создать"
    if request.method == "POST":
        form = BlogPostModelForm(request.POST, request.FILES)
        if form.is_valid():
            new_blog = form.save(commit=False)
            new_blog.author = request.user
            new_blog.date_published = datetime.now()
            new_blog.save()
            return redirect("blog:index")
    else:
        form = BlogPostModelForm()
    return render(request, 'blog/create_update_blog.html', {"title": title, "form": form, "action": action})

def is_owner(func):
    def wrapper(request, *args, **kwargs):
        blog_id = pk=kwargs["pk"]
        if blog_id:
            blog = BlogPost.objects.get(pk=kwargs["pk"])
            if blog.author == request.user or request.user.is_superuser:
                return func(request, *args, **kwargs)
        return redirect("blog:index")
    return wrapper

@is_owner
@login_required
def update_blog(request, pk):
    action = "Обновить"
    blog = BlogPost.objects.get(pk=pk)
    title = f"Редактирование {blog.title}"
    if request.method == "POST":
        form = BlogPostModelForm(request.POST, request.FILES, instance = blog)
        if form.is_valid():
            form.save()
            return  redirect("blog:blog_detail", pk=pk)
    else:
        form = BlogPostModelForm(instance=blog)
    return render(request, 'blog/create_update_blog.html',{"title": title, "form": form, "action": action})


@is_owner
@login_required
def delete_blog(request, pk):
    blog = BlogPost.objects.get(pk=pk)
    blog.delete()
    return redirect("blog:index")

def contacts(request):
    title = "Контакты"
    return render(request, 'blog/contacts.html', {"title": title})

site_django/blog/templates/blog/blog_detail.html
 {% extends 'blog/layout.html' %}
 {% load static %}
 {% block title %} {{blog.title}} {% endblock %}


 {% block static %}
 <link  rel="stylesheet" href="{% static 'blog/css/blog_detail.css' %}">
 {% endblock %}

 {% block content %}
      {% if not exception %}
      <div class="blog_detail">
          <a class="arrow btn btn-light" href="{% url 'blog:blog_detail' pk=blog.id %}?post=prev">
              <i class="fa fa-angle-left"></i>
          </a>
          <div class="news">
              <div class="content">
                   <h3 class="blog_title">{{ blog.title }}</h3>
                  <img src="{{blog.image.url}}">
                  <div class="blog_text"><a>{{ blog.content|linebreaks }}</a></div>
                  <div class="blog_info">
                       <a>{{blog.author}}</a>
                       <a>{{blog.date_published}}</a>
                  </div>
              </div>
              <div class="comments">
                  {% if comments %}
                    {% for comment in comments %}
                        <div class="comment">
                            <a class = "comment_author">
                                <img src="{% static 'blog/img/user2.png' %}" style="width: 40px; margin: 10px">
                                {{comment.author}}
                            </a>
                            <a class="comment_text">
                                {{comment.text}}
                            </a>
                            <a class = "comment_date" style="align-self: flex-end">
                                {{comment.date_published}}
                            </a>
                         </div>
                    {% endfor %}
                  {% else %}
                    <a class="no_comments">Комментариев нет</a>
                  {% endif %}

                   {% if user.is_authenticated%}
                        <div class="com_form">
                            <h3>Ваш комментарий</h3>
                            <form method="POST">
                                {% csrf_token%}
                                {{ form.as_p }}
                                <button type="submit" class="btn btn-success btn-send">
                                    Отправить
                                </button>
                            </form>
                        </div>
                  {% else %}
                        <h3>Авторизуйтесь, чтобы оставлять комментарии</h3>
                  {% endif %}
             </div>
          </div>
          <a class="arrow btn btn-light" href="{% url 'blog:blog_detail' pk=blog.id %}?post=next">
              <i class="fa fa-angle-right"></i>
          </a>
      </div>
      {% else %}
        <div class="error">
            <a>{{exception}}</a>
            <a href="{% url 'blog:index' %}">Вернуться к списку</a>
        </div>
      {%endif %}
{% endblock %}

site_django/blog/templates/blog/blog_list.html
 {% extends 'blog/layout.html' %}
 {% load static %}
 {% block title %} Блог {% endblock %}


 {% block static %}
    <link  rel="stylesheet" href="{% static 'blog/css/blog_list.css' %}">
 {% endblock %}

 {% block content %}
    {% if perms.blog.add_blogpost %}
        <a class="btn btn-success btn-create" href="{% url 'blog:create_blog' %}">Создать блог</a>
    {% endif %}

   <form class = "form-group form-search" method="GET">
       <input type="text" name="search" class="form-control input-search" style="200px"  placeholder="Поиск">
       <input type="submit" class="btn btn-primary btn-search" value="Найти">
   </form>

    <div class="sort-date">
        Сортировать по дате:
        <a href="?sort=newest{% if search_query %}&search={{ search_query }}{% endif %}">Новые</a> |
        <a href="?sort=oldest{% if search_query %}&search={{ search_query }}{% endif %}">Старые</a>
    </div>

   <div class="list">
     {% for blog in page_obj %}
        <div class="blog"

        style="background-image: linear-gradient(90deg, white, white, transparent),
            url({{ blog.image.url }});
        background-position: right;">
            <div class="content">
                <a href="{{blog.get_absolute_url}}">{{blog.title | truncatechars:40}}</a>
            </div>
            <div class="blog_info">
                <a> {{blog.content | truncatechars:100}}</a>
                <a style="color: gray">{{blog.date_published}}</a>
            </div>
            <a style="color: gray"> by {{blog.author}}</a>
            {% if blog.author == request.user or request.user.is_superuser %}
                 <a class="btn btn-outline-warning"  href="{% url 'blog:update_blog' pk=blog.id %}" style="margin: 1% 0 0 2%" ><i class="fa fa-pen"></i></a>
                 <a class="btn btn-outline-danger"  href="{% url 'blog:delete_blog' pk=blog.id %}" style="margin: 1% 0 0 2%" ><i class="fa fa-trash"></i></a>
            {% endif %}
        </div>
       <br>
     {% endfor %}
   </div>

    <div class="pagination">
        <span class="step-links">
            {% if page_obj.has_previous %}
                <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_number }}">previous</a>
            {% endif%}

            <span class="current">
                Page {{ page_obj.number}} of {{ page_obj.paginator.num_pages }}
            </span>

            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">next</a>
                <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </span>
    </div>
 {% endblock %}

site_django/blog/templates/blog/contacts.html
 {% extends 'blog/layout.html' %}
 {% load static %}
 {% block title %} Контакты {% endblock %}

{% block static %}
<link rel="stylesheet" href="{% static 'blog/css/contacts.css' %}">
{% endblock %}

{% block content %}
<div class="contacts-container">
    <h1 class="title-contacts">Контакты</h1>
    
    <div class="contact-section">
        <h2>Техническая поддержка.</h2>
        <p>Возникла проблема с устройством? Мы найдем для вас лучший вариант поддержки.</p>
        <p>Телефон 8 (800) 555-82-35.</p>
        <p>Режим работы Ежедневно с 10:00 до 20:00.</p>
        <br>
    </div>

    <div class="contact-section">
        <h2>Сотрудничество и реклама.</h2>
        <p>Принимаем предложения по совместному продвижению продуктов и услуг.</p>
        <p>example233@gmail.com</p>
        <br>
    </div>
</div>
{% endblock %}

site_django/blog/templates/blog/create_update_blog.html
 {% extends 'blog/layout.html' %}
 {% load static %}
 {% block title %} Блог {% endblock %}


 {% block static %}
    <link  rel="stylesheet" href="{% static 'blog/css/create_update_blog.css' %}">
 {% endblock %}

 {% block content %}
    <div class="createform">
        <form method="POST" enctype = "multipart/form-data">
            <div class="form">
                {% csrf_token %}
                {{ form.title }}<br>
                {{ form.content }}<br>
                {{ form.image }}<br>
                <button type="submit" class="btn btn-success" style="margin: 10px 0 2% 0">{{ action }}</button>
            </div>
        </form>
    </div>
 {% endblock %}

site_django/blog/templates/blog/layout.html
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}

        {% endblock %}
    </title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.6/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">

    <link rel="stylesheet" href="{% static 'blog/css/layout.css' %}">
    <link rel="shortcut icon" href="{% static 'blog/img/site_icon.png' %}">
    {% block static %}

    {% endblock %}
</head>
<body>
    <div class="header">
        <div class="left_side">
            <a  class = "btn btn-primary main" href="{% url 'blog:index' %}">Главная страница</a>
            <a  class = "btn btn-primary contacts" href="{% url 'blog:contacts'%}">Контакты</a>
        </div>

        <div class="middle">
            <img class="logo" src="{% static 'blog/img/лого3.webp' %}"><div class="title"> МАСТЕРПК БЛОГ</div>
        </div>

         <div class="right_side">
             {% if user.is_authenticated %}
                <a class = "profile btn btn-primary" href ="{% url 'users:profile' %}" > <img src="{% static 'blog/img/person.png' %}" alt=""> {{ user.username }}</a>
                {% if user.is_superuser %}
                    <a class="btn btn-warning" href="{% url 'admin:index' %}" style="margin-right: 10px"><i class = "fa fa-cog"></i></a>
                {% endif %}
                 <form class="log_out_form" action="{% url 'users:logout' %}" method="POST">
                    {% csrf_token %}
                     <button type="submit" class="btn btn-primary btn-exit"><i class="fa fa-sign-out-alt"></i>Выход</button>
                 </form>
             {% else %}
                <a class="btn btn-success" href ="{% url 'users:login' %}">Вход</a>
                <a class="btn btn-primary" href="{% url 'users:register' %}">Регистрация</a>
             {% endif %}
        </div>
    </div>
    <div style="height: 6%"></div>
    {% block content %}

    {% endblock %}
</body>
</html>